name: CI
on:
  # Triggers the workflow on push or pull request events but only for the
  # master branch.
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in
# parallel.
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Run the build for each one of these configurations in parallel.
    strategy:
      matrix:
        # The `${{ matrix.mainboard }}` variable is replaced with each of these.
        mainboard:
          - aeeon/up
          - aeeon/upxtreme
          - amd/rome
          - ampere/jade
          - bytedance/g220a
          - cubie/board
          - digitalloggers/atomicpi
          - hpe/dl360gen10
          - intel/generic
          - intel/hw
          - intel/minplatform
          - intel/s2600
          - lenovo/hr630
          - lenovo/sr630
          - lenovo/thinkpad
          - marvel/macchiatobin
          - opentitanpilot/dresden
          - pcengines/apu
          - pcengines/apu2
          - seeed/beaglev
          - slimboot
          - st/st32mp1517c
          - tyan7106
          - walmart/robot

      # Do not cancel all jobs steps if a single one fails.
      fail-fast: false

    # Steps represent a sequence of tasks that will be executed as part of the
    # job.
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can
      # access it.
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Make ${{ matrix.mainboard }} kernel
        run: |
          cd $GITHUB_WORKSPACE/${{ matrix.mainboard }}
          make fetch
          make flashkernel
